name: Draft release
on:
  milestone:
    types: [closed]

jobs:
  draft-release:
    name: Draft release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate release notes
        uses: docker://decathlon/release-notes-generator-action:2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release notes artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-notes
          path: release_file.md

      - name: Setup GitVersion
        run: dotnet tool install --global GitVersion.Tool --version 5.6.0

      - name: Fetch git tags
        run: git fetch --tags --unshallow

      - name: Get version
        run: dotnet-gitversion /output buildserver

      - name: Read release notes
        id: NOTES
        uses: juliangruber/read-file-action@v1
        with:
          path: release_file.md

      - name: Draft new release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.GitVersion_LegacySemVerPadded }}
          release_name: v${{ env.GitVersion_LegacySemVer }}
          body: |
            # ${{ github.event.repository.name }} v${{ env.GitVersion_LegacySemVer }} has been released
            ```
            Install-Package ${{ github.event.repository.name }} -Version ${{ env.GitVersion_NuGetVersionV2 }}
            ```
            ```
            dotnet add package ${{ github.event.repository.name }} --version ${{ env.GitVersion_NuGetVersionV2 }}
            ```
            ${{steps.NOTES.outputs.content}}
          draft: true
          prerelease: ${{ env.GitVersion_PreReleaseLabel != '' }}
